### PR TITLE
Style: Easier to read Python code style

### PR DESCRIPTION
**Pull request by benmezger**
This uses `black` to format code in a more readable and standard way with the code base.

### CODE REVIEW

**Comment by benmezger** [comment]
@s0md3v any reason why this wasn't accepted?

**Comment by s0md3v** [comment]
Because I prefer single quotes :)

**Comment by benmezger** [comment]
Yeah, I get that, but you don't really use single quotes every where. Also this commit brings other changes other than single quotes.

**Comment by s0md3v** [comment]
I wrote this a year ago when I was a complete beginner. It's basically trash and I do not maintain it anymore. However, I have planned to rewrite this with new features and all, once I am free.

I apologize for not including a style guide :)

**Pull request closed without merging**
